dist: trusty
sudo: false
notifications:
  email: false
env:
- RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
  - stage: build and release to github
    language: java
    jdk: oraclejdk8
    install: skip
    script: ./gradlew clean build -x test
    before_deploy:
    - git config --local user.name "Build Bot"
    - git config --local user.email "buildbot@example.com"
    - git tag -f $RELEASE_TAG
    deploy:
      provider: releases
      api_key: bc626cd63f25c86e487a31413a2aa418f072cde0
      file: "build/libs/mediabase-1.0-SNAPSHOT.war"
      skip_cleanup: true
  - stage: deploy to test
    language: java
    script:
    - echo "Downloading $RELEASE_TAG"
    - wget -P build/libs https://github.com/bdiramio/mediabase/releases/download/$RELEASE_TAG/mediabase-1.0-SNAPSHOT.war
    before_deploy:
    - echo "Deploying $RELEASE_TAG to test"
    deploy:
      provider: cloudfoundry
      api: https://api.sys.pcf.paltraining.perficient.com
      username: Bobd@Well-B.com
      password: cQmHURYj
      organization: Bobd
      space: test
